### ISSUE TITLE
Confused where to start server/create db

### ISSUE THREAD

**Issue by KristerV** [eyedouble/couchdb#1]
Total beginned here and can't quite understand how to use this package. Perhaps a Getting Started section in the readme?

**Comment by ivanwel** [comment]
Hi krister,

Thanks for using CouchDb Erlang/Elixir. 

Please have a look at my test suite, this will give you a good idea of how to use it in practice. 

Your suggestion is valid, and when I have a chance I will make the readme a bit more detailed.

Out of interest are using erlang or elixir and are you planning to use it professionally or in your personal capacity?

Greetings

**Comment by KristerV** [comment]
I'm using Elixir in my new product. So rather small at the moment, hoping to scale :)

**Comment by ivanwel** [comment]
Cool! Have a look at the docs here: https://hexdocs.pm/couchdb/couchdb.html#

Its quite simple, create a database record, then pass that record into the couchdb_document functions.

**Comment by KristerV** [comment]
Okay I put good effort into using it. The main confusing thing that took a long time to understand was that it didn't mention anywhere that `:couchdb` and it's fellows like `:couchdb_documents` are _all_ global variables.

After realizing that everything got much more easy. I will try to implement this properly again later. Right now I made a faster memory-only solution for prototyping.

**Comment by ivanwel** [comment]
Cool good to hear!In memory is the way to go indeed we use ETS for our test suite and couch for production. Can I close this issue?On 27 Jan 2020 2:25 PM, Krister Viirsaar <notifications@github.com> wrote:Okay I put good effort into using it. The main confusing thing that took a long time to understand was that it didn't mention anywhere that :couchdb and it's fellows like :couchdb_documents are all global variables.
After realizing that everything got much more easy. I will try to implement this properly again later. Right now I made a faster memory-only solution for prototyping.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
On 27 Jan 2020 2:25 PM, Krister Viirsaar <notifications@github.com> wrote:Okay I put good effort into using it. The main confusing thing that took a long time to understand was that it didn't mention anywhere that :couchdb and it's fellows like :couchdb_documents are all global variables.
After realizing that everything got much more easy. I will try to implement this properly again later. Right now I made a faster memory-only solution for prototyping.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
On 27 Jan 2020 2:25 PM, Krister Viirsaar <notifications@github.com> wrote:Okay I put good effort into using it. The main confusing thing that took a long time to understand was that it didn't mention anywhere that :couchdb and it's fellows like :couchdb_documents are all global variables.
After realizing that everything got much more easy. I will try to implement this properly again later. Right now I made a faster memory-only solution for prototyping.

**Comment by KristerV** [comment]
Yeah lets close the issue, once I learn to use this properly I'll make a PR with doc fixes. Thanks for your time and library!

**Comment by ivanwel** [comment]
Hi Krister, sounds fantastic let me know when you are starting on that PR im happy to collaborate!On 28 Jan 2020 10:33 AM, Krister Viirsaar <notifications@github.com> wrote:Closed #1.

**Comment by KristerV** [comment]
I couldn't go back to couchdb, beacuse turns out I need insane performance and PostgreSQL is probably better at this.
